spring:
  application:
    name: mscartoes
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${EUREKASERVER_HOST:localhost}:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}


mq:
  queues:
    card-issuance: card-issuance

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/logs-file.log